### ISSUE TITLE
[BLOCKING] medical_standards - still broken after merge

### ISSUE THREAD

**Issue by iberi22** [iberi22/local-llm.OrionHealth#63]
## CRITICAL: medical_standards package still has compilation errors

After merging PRs, there are still blocking errors in packages/medical_standards/

### ERRORS TO FIX

1. medications.dart line 825: Unterminated string literal
commonDosages: ['100mg 2
This corrupts the entire file. FIX: Find and properly close this string.

2. medications.dart line 826: Cascading errors from line 825
The string break causes mg day being parsed as identifiers
FIX: Close the string properly on line 825

3. medical_standards.dart lines 123-130: Export directives AFTER declarations
Dart requires exports to come before any code
FIX: Move all export statements to top of file

4. loinc.dart lines 1501-1515: Invalid syntax
Uses === operator which doesn't exist in Dart
Has invalid constant values and malformed code
FIX: Rewrite this section correctly

5. medical_context_categories.dart lines 93, 150, 331: Duplicate elements in const sets
FIX: Remove duplicate entries

6. profile_analyzer.dart: 
Missing 'ophthalmology' enum constant
Wrong parameter names for RelevantStandards constructor
FIX: Add missing enum value or use correct constant

7. medical_context_provider.dart line 219: List<void> type inference
FIX: Use proper type or List<Future>

8. snomed.dart line 23: const constructor with non-const super
FIX: Remove const keyword

### VERIFICATION
After fixes run:
cd packages/medical_standards
dart analyze lib/

Must show No issues found for lib/ folder

### FILES
- packages/medical_standards/lib/medications/medications.dart
- packages/medical_standards/lib/medical_standards.dart
- packages/medical_standards/lib/loinc/loinc.dart
- packages/medical_standards/lib/onboarding/medical_context_categories.dart
- packages/medical_standards/lib/onboarding/profile_analyzer.dart
- packages/medical_standards/lib/services/medical_context_provider.dart
- packages/medical_standards/lib/snomed/snomed.dart

**Comment by iberi22** [comment]
Requirements changed - now tracking in new issue
